### ISSUE TITLE
When signing in, provide the user with feedback if the username / password is wrong. Add remember me and forgot password.

### ISSUE THREAD

**Issue by Ic4rus90** [boolean-uk/team-dev-client-ex-2410-team2#12]

**Comment by stian96** [comment]
Need to implement a new page where users are redirected when they click on the "Forgot password?" link. On this page, they need to enter their email address to receive instructions on how to reset their password

**Comment by Brandsegg** [comment]
Looks good! Make a pull request and I will review it!
