### ISSUE TITLE
Add bio info page

### ISSUE THREAD

**Issue by h602121** [boolean-uk/team-dev-client-ex-2410-team2#16]
- Add placeholder text in input field
- Add character count for input field
- Add character limit (max 300) for input field
- Remove "*required" to match figma design

![Image](https://github.com/user-attachments/assets/929266d3-f412-4d2f-b77c-3c686992cf08)

![Image](https://github.com/user-attachments/assets/32fa70a3-8b6d-431f-a249-a767e461a4e0)

**Comment by uerbzr** [comment]
Can we see the Figma design on here?
