### ISSUE TITLE
Create a post domain

### ISSUE THREAD

**Issue by thomamn** [boolean-uk/team-dev-client-ex-2410-team2#19]
When a user is logged in, they should be redirected to the dashboard which can connect to endpoints:

get all posts, sorted by age
post new post
get post by id or title
possibly the ability to delete ones own posts
get all users that are logged in

P.S: Not sure if these are indeed tasks that must be fulfilled or if this is the appropriate way of writing them out. Feel free to change things if you feel these suggestions are wrong.

**Comment by JHalvor** [comment]
wrong tag, not frontend is backend. will create two new issues to also split endpoints and domain creation
