### ISSUE TITLE
Implement "My Cohort" list in dashboard

### ISSUE THREAD

**Issue by ThomasNWiik** [boolean-uk/team-dev-client-ex-2410-team2#25]
Implement the My Cohort list as a component, and import it into Dashboard.
Do populate the list, edit the user table in Neon: 
![Image](https://github.com/user-attachments/assets/fc63b69d-4aab-436d-b203-a0cb6cc076c2)
![Image](https://github.com/user-attachments/assets/5e036cf0-af12-498c-8383-99237e4386a3)

When clicking the three dots, display the following: 
![Image](https://github.com/user-attachments/assets/c3c5d8b6-21b5-4290-9be8-d29720a4b141)

**Comment by Ic4rus90** [comment]
@uerbzr
