### ISSUE TITLE
Change functionality when clicking three dots on a post.

### ISSUE THREAD

**Issue by Ic4rus90** [boolean-uk/team-dev-client-ex-2410-team2#26]
When a user clicks the three dots in the right upper-hand corner of a post, the following modal should be displayed: 
https://www.figma.com/design/j9QIHvgM0wOVw3xDe9KdWB/My-Copy%3A-Cohort-Manager-app---Designs?node-id=419-17468&t=UTLALoz7K4DbViHp-4

 ![Image](https://github.com/user-attachments/assets/58541c23-afda-4431-90b6-2416072de134)

If the user clicks edit post, open the existing edit post modal. 

If the user clicks delete post, open the following modal: 
https://www.figma.com/design/j9QIHvgM0wOVw3xDe9KdWB/My-Copy%3A-Cohort-Manager-app---Designs?node-id=419-17469&t=UTLALoz7K4DbViHp-4
![Image](https://github.com/user-attachments/assets/4800e6e0-a88f-4b5b-a400-6c5f1722b9bf)

API calls will be implemented later.
The three dots should only be visible if it's the post of the user OR if the user is a teacher.

**Comment by stian96** [comment]
This functionality: "The three dots should only be visible if it's the post of the user OR if the user is a teacher", is not implemented since I currently can't access the logged-in user object.
