### ISSUE TITLE
Research how to get access to the user object when signed in, to get properties such as role and ID.

### ISSUE THREAD

**Issue by Ic4rus90** [boolean-uk/team-dev-client-ex-2410-team2#39]

**Comment by DanielMjosRoli** [comment]
User-ID is stored in token. Only the User-ID, token creation and token expiration is stored in the token. For info on the role an API call for full User body is required. Unless it is stored somewhere else :/

**Comment by DanielMjosRoli** [comment]
Can bruke UserID slik:
  const { token } = useAuth();
  const userID = jwt_decode(token);
